export const ProductData = [
  { name: "Smartphone", category: "Electronics", price: 500, image: "https://i.gadgets360cdn.com/products/large/vivo-t2-5g-db-709x800-1681200173.jpg" },
  { name: "Laptop", category: "Electronics", price: 1000, image: "https://5.imimg.com/data5/WT/WU/MY-13922529/hp-laptop.jpg" },
  { name: "Fitness Tracker", category: "Fitness", price: 80, image: "https://m.media-amazon.com/images/I/61YwaovfYFL._AC_UF1000,1000_QL80_.jpg" },
  { name: "Wireless Earbuds", category: "Electronics", price: 90, image: "https://hammeronline.in/cdn/shop/files/ko-pro-02.webp?v=1701418055&width=1080" },
  { name: "Cricket Bat", category: "Sports", price: 60, image: "https://cdnmedia.dsc-cricket.com/media/catalog/product/cache/6d9f53a3f26f3a62c1c1c9add7c6ad94/k/r/krunch-pro-english-willow-cricket-bat-2023.jpg" },
  { name: "History Book Set", category: "Books", price: 40, image: "https://cdn.pixelspray.io/v2/black-bread-289bfa/HrdP6X/original/hamleys-product/491947919/665/491947919.webp" },
  { name: "Smart Watch", category: "Electronics", price: 130, image: "https://p.globalsources.com/IMAGES/PDT/B1183640554/KW76-Smart-Watch.jpg" },
  { name: "Dumbbell Set", category: "Fitness", price: 50, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRvENGlWyAt17IWhuq4ZsMjHl4qU433Vi-3tHdTYOlbTCvM-ccvm9biTce1iiQaZZus6U&usqp=CAU" },
  { name: "Bluetooth Speaker", category: "Electronics", price: 70, image: "https://m.media-amazon.com/images/I/71QIESVX4jL._AC_UF1000,1000_QL80_.jpg" },
  { name: "Running Shoes", category: "Fitness", price: 80, image: "https://contents.mediadecathlon.com/p2153253/ce01a41e66153a9e1837bd6b024c9066/p2153253.jpg?format=auto&quality=70&f=650x0" },
  { name: "Camera", category: "Electronics", price: 600, image: "https://in.canon/media/image/2023/05/19/b89bed4e21e540f985dedebe80166def_EOS+R100+RF-S18-45mm+Front+Slant.png" },
  { name: "Gaming Console", category: "Electronics", price: 350, image: "https://image.cnbcfm.com/api/v1/image/106983027-1638381923655-Gaming_Handheld_Leaning.jpg?v=1638382019" },
  { name: "Yoga Mat", category: "Fitness", price: 20, image: "https://www.juplayworld.com/JuplayWorldBackEndImage/ProductImages/arnv-yoga-mat-699.jpg" },
  { name: "Headphones", category: "Electronics", price: 75, image: "" },
  { name: "Cricket Gloves", category: "Sports", price: 35, image: "" },
  { name: "Ancient History Book", category: "Books", price: 25, image: "" },
  { name: "Fitness DVD Set", category: "Fitness", price: 30, image: "" },
  { name: "Wireless Mouse", category: "Electronics", price: 25, image: "" },
  { name: "Treadmill", category: "Fitness", price: 300, image: "" },
  { name: "Portable Charger", category: "Electronics", price: 20, image: "" },
  { name: "Soccer Ball", category: "Sports", price: 15, image: "" },
  { name: "Biography Book", category: "Books", price: 50, image: "" },
  { name: "Weight Bench", category: "Fitness", price: 80, image: "" },
  { name: "Tablet", category: "Electronics", price: 180, image: "" },
  { name: "Gaming Mouse", category: "Electronics", price: 40, image: "" },
  { name: "Protein Powder", category: "Fitness", price: 25, image: "" },
  { name: "Wireless Keyboard", category: "Electronics", price: 30, image: "" },
  { name: "Cricket Pads", category: "Sports", price: 45, image: "" },
  { name: "World History Book", category: "Books", price: 35, image: "" },
];
